### ISSUE TITLE
Create Orc Faction

### ISSUE THREAD

**Issue by Theawesomeboophis** [Theawesomeboophis/Cataclysm-DDA-Boophis#2]
# Describe the solution you'd like
Create new Orc faction.

# Describe alternatives you've considered
Recreating orcs to fit into current faction.

**Comment by Xpyder** [comment]
tag me with an @ if you need some help

**Comment by Theawesomeboophis** [comment]
New faction is probably best way to go.

**Comment by Theawesomeboophis** [comment]
I will work on https://github.com/CleverRaven/Cataclysm-DDA/issues/45162.
Can you do the Orc stuff, I'll check if it works.

**Comment by Xpyder** [comment]
I don't know that I have the time to really flesh it out.
If you do the core code (or something close to it) I can probably find time to make modifications so the game will accept them.

alternatively, if you create the basic fleshing out of them (looks like "some description" hits like a goblin warrior, based off of red demon spider in magiclysm etc) it will be easier for people with more code experience to translate it into a language the game will understand.  I'm not committing to anything, but it will make it easier for you and other people to collaborate on it

**Comment by Theawesomeboophis** [comment]
Ok

**Comment by Theawesomeboophis** [comment]
> I don't know that I have the time to really flesh it out.
> If you do the core code (or something close to it) I can probably find time to make modifications so the game will accept them.
> 
> alternatively, if you create the basic fleshing out of them (looks like "some description" hits like a goblin warrior, based off of red demon spider in magiclysm etc) it will be easier for people with more code experience to translate it into a language the game will understand. I'm not committing to anything, but it will make it easier for you and other people to collaborate on it

How do I do that?

**Comment by Theawesomeboophis** [comment]
Created the orc faction, going smoothly so far, gonna try and fix dinosaurs.json as well.

**Comment by Theawesomeboophis** [comment]
Faction created, might need improvements.

**Comment by Theawesomeboophis** [comment]
Finished.
