### ISSUE TITLE
Qianzhousaurus Is Broken

### ISSUE THREAD

**Issue by Theawesomeboophis** [Theawesomeboophis/Cataclysm-DDA-Boophis#3]
# Describe the bug
Lines  
"symbol": "D",
 "volume": "5000 ml",
  },

**Comment by Theawesomeboophis** [comment]
I don't know how to fix .json bugs.

**Comment by Theawesomeboophis** [comment]
I'll work on content, you can fix bugs if you want to, does that sound ok?

**Comment by Drafting-Goblin** [comment]
How much of the wiki/new contributors guide(https://github.com/CleverRaven/Cataclysm-DDA/wiki/Guide-to-adding-new-content-to-CDDA-for-first-time-contributors) did you go through Theaweseomboophis? I'm fairly new to this as well, but the wiki and that guide have been incredibly helpful in guiding me. Alongside those, in the main CDDA folder there is a subfolder labeled 'doc' that has additional documentation.

**Comment by Theawesomeboophis** [comment]
I just read the monster section, going to go read the doc for more info.

**Comment by Drafting-Goblin** [comment]
Nice! I'm currently working on the nothronychus. This is my first time working on a monster. It's definitely the most complicated thing I've worked on for CDDA so far lol.

**Comment by Theawesomeboophis** [comment]
Ok, I read the instructions, but I don't really understand how to fix the above problem.

**Comment by Theawesomeboophis** [comment]
Also, send merge request after you finish Nothronychus.

**Comment by Theawesomeboophis** [comment]
I appreciate it.

**Comment by Drafting-Goblin** [comment]
Can you describe the above problem a little more?

**Comment by Theawesomeboophis** [comment]
The : symbol is red in the above lines and in the last line the } is red, meaning I messed up something.

**Comment by Theawesomeboophis** [comment]
Its the last dinosaur in dinosaurs.json.

**Comment by Theawesomeboophis** [comment]
I've tried fixing it and I think it might be a spacing problem.

**Comment by Drafting-Goblin** [comment]
spacing is tricky with these, hence the reason we need to lint stuff before submitting it. It seems like you might be missing a }, between the above monster and the one you are adding.

**Comment by Theawesomeboophis** [comment]
ok, I'll add that.

**Comment by Theawesomeboophis** [comment]
It's a spacing problem.

**Comment by Drafting-Goblin** [comment]
What text editing program are you using?

**Comment by Theawesomeboophis** [comment]
I am using Github directly.

**Comment by Drafting-Goblin** [comment]
Interesting, I didn't know that was possible (I'm still pretty new). I've had good results with notepad++, I mainly use Visual Studio but it's a bit overkill for just JSON files. (I'm also on Windows).

**Comment by Theawesomeboophis** [comment]
Yeah if you go to file on Github there is a edit button on top right.

**Comment by Theawesomeboophis** [comment]
I just added this dinosaur to the spawn list for DinomodLabFinale.

**Comment by Theawesomeboophis** [comment]
If I fix the actual monster, and everything works correctly, It should spawn in that location.

**Comment by Drafting-Goblin** [comment]
Nice!

**Comment by Theawesomeboophis** [comment]
Quick question, how do I make this branch even with cleverraven again?

**Comment by Drafting-Goblin** [comment]
I think you would need to commit your changes and then submit a Pull Request. I use the Github desktop app to manage my branches and PRs so it might be a bit different than managing it on the site.

**Comment by Drafting-Goblin** [comment]
Oh wait, or did you mean revert your changes and make it identical to the main CDDA one?

**Comment by Theawesomeboophis** [comment]
No, I meant add the changes from new experimental build to this fork.

**Comment by Drafting-Goblin** [comment]
Ah, I'm not sure how to manage that from the site. On the desktop app it's a button. Sometimes I have to press it, other times it auto updates

**Comment by Theawesomeboophis** [comment]
I have desktop, which button is it?

**Comment by Drafting-Goblin** [comment]
There is the big button that states the current repository, then on the right is the current branch and then right of that is the button. I forget what it says (currently in the middle of editing something). It should say something like pull from origin and it should list the last time this was done.

**Comment by Theawesomeboophis** [comment]
How do I minimize the tab, i accidentally fullscreened it earlier while working on a pull request.

**Comment by Drafting-Goblin** [comment]
I'm not entirely sure, sorry.

**Comment by Theawesomeboophis** [comment]
I'll just reinstall and see if that fixes window size.

**Comment by Theawesomeboophis** [comment]
I'm still not seeing button.

**Comment by Drafting-Goblin** [comment]
![image](https://user-images.githubusercontent.com/73050654/97771530-0ad59f00-1b14-11eb-8e03-f131f4133123.png)

The "Fetch origin" button is what I've used.

**Comment by Theawesomeboophis** [comment]
What version are you on?

**Comment by Drafting-Goblin** [comment]
I think it's running off of the up-to-date version of CDDA.

**Comment by Theawesomeboophis** [comment]
No, I mean Github Desktop version.

**Comment by Drafting-Goblin** [comment]
2.5.6

**Comment by Theawesomeboophis** [comment]
Oh, I see it now, I had to clone repo first.

**Comment by Theawesomeboophis** [comment]
sorry.

**Comment by Drafting-Goblin** [comment]
No worries.

**Comment by Theawesomeboophis** [comment]
I'm new to the whole contributing thing, and as you can see from everything I've added here, I'm not that good at programming.

**Comment by Drafting-Goblin** [comment]
No worries, we all start somewhere. I'm fairly new as well, I've only started contributing like a week ago and I only have three PRs under my belt. It can definitely be a bit overwhelming, but the guides are a good starting place. Also, adding these dinos in is the most challenging thing I've attempted so far, they are kind of complex. You could always try something a little less complex for practice.

**Comment by Theawesomeboophis** [comment]
Thanks

**Comment by Theawesomeboophis** [comment]
Good job with your work on nothronychus btw.

**Comment by Theawesomeboophis** [comment]
I tried fixing it again by adding Type monster but made it even worse.

**Comment by Drafting-Goblin** [comment]
Taking a look at it, it looks like some spacing issues and you missed a few commas on a couple of lines. The mosasaurus has its type defined both at the top of its entry and the bottom. It only needs to be defined once. The weight for the qianzhousaurus seems to be missing units. I recommend using something like notepad++ as it will be able to display spacing a bit better.

**Comment by Drafting-Goblin** [comment]
also thanks :D

**Comment by Theawesomeboophis** [comment]
I didn't change mosasaurus, but I will try fixing weight today.

**Comment by Xpyder** [comment]
Also if you're new and getting those red : I'd copy paste the whole file you're editing (with your changes) here: https://jsonformatter.curiousconcept.com/

that should give you more clear error messages and should help with debugging

**Comment by Theawesomeboophis** [comment]
Thanks, Xpyder.

**Comment by Theawesomeboophis** [comment]
I'll try and fix it.

**Comment by Theawesomeboophis** [comment]
Do I download notepad++ directly from releases and if so, which asset do I download, because the problem is that I'm not using a proper json editor.

**Comment by Theawesomeboophis** [comment]
Nevermind, I downloaded it, gonna try and fix and then I'll post fix here.

**Comment by Theawesomeboophis** [comment]
Almost fixed, now only volume and symbol are bugged.

**Comment by Theawesomeboophis** [comment]
Ending is problem, don't know how to fix it.

**Comment by Drafting-Goblin** [comment]
I'd take a look at other JSON files and see how they end. I suspect it's an issue with commas. The cool thing with JSON files is you can make yours look like all of the others in the file and that should get your on the right path. I've found this guide in the wiki to be helpful as well (https://github.com/CleverRaven/Cataclysm-DDA/wiki/New-Contributors-Guide-Troubleshooting). It seems like you're making decent progress on Qianzhousaurus. I took a break for Halloween but I'm almost done Nothronychus. I want to do some testing to make sure that everything works as intended.

**Comment by Drafting-Goblin** [comment]
I submitted the nothronycus PR. I think it makes sense to submit them individually rather than all at once as each dino needs a few different files to function, and it would be a lot of work to sort through four dinos worth of files in one PR.

**Comment by Theawesomeboophis** [comment]
That does make more sense because it might take a little while to fix
everything and get it ready for merge.

**Comment by Theawesomeboophis** [comment]
Everytime I fix a bug with these lines another emerges, confused as to how to fix this properly.

**Comment by Theawesomeboophis** [comment]
Fixed it, and made Qianzhousaurus more complex.
