### ISSUE TITLE
Make orcs spawn in world

### ISSUE THREAD

**Issue by Theawesomeboophis** [Theawesomeboophis/Cataclysm-DDA-Boophis#4]
# Describe the solution you'd like
Add orcs to wilderness and make orc camps
# Describe alternatives you've considered
Making orcs spawn in packs instead of organized camps.

**Comment by Xpyder** [comment]
from #1 
> I'm gonna set them to spawn in cities, as Orcs usually live in groups or tribes, an alternative to this could be to rework Goblin camps to spawn orcs, and then make the orc camps a separate building somehow.

I think you have the right idea.  I've never added area spawning yet, but my understanding is you create a map "tile" and then add it to spawn groups so the game knows where to put it and how frequently.

My guess would be eventually to copy some of the goblin tiles, give them orc id names instead (so they're unique) and then add those ids to the spawn lists.

The easiest place to start figuring out how to do this is probably finding a goblin camp you like the look of, then searching for it's id to see where it's referenced

**Comment by Xpyder** [comment]
I'd start by looking at some of the map tiles you can find here: [/data/json/mapgen](https://github.com/Theawesomeboophis/Cataclysm-DDA-Boophis/tree/master/data/json/mapgen)

It might look like unreadable code for a sec, but if you look carefully you'll see it's actually just the literal tile laid out with symbols that are tied to things immediately after.

![image](https://user-images.githubusercontent.com/12039454/98049567-c59bc080-1de4-11eb-8c12-b85ada0f7abf.png)

**Comment by Theawesomeboophis** [comment]
Ok thanks, sorry btw, I'm only available to commit on weekends.

**Comment by Xpyder** [comment]
it's fine, I tend to do for a while then drop off, part of why I'm trying to help hand you the tools you'll need so you aren't dependent on me

**Comment by Drafting-Goblin** [comment]
That is an informative guide. I plan on doing some mapgen stuff when my school stuff calms down a bit. Thank you very much for the additional information :D

**Comment by Theawesomeboophis** [comment]
Orcs and Ogres almost complete.
