### ISSUE TITLE
What do you have in mind?

### ISSUE THREAD

**Issue by actual-nh** [Theawesomeboophis/Cataclysm-DDA-Boophis#7]
Hi. Thank you for the access; what do you have in mind my doing? (Sorry it took me a bit to respond, but the test result inconsistencies are driving me a tad bit nuts... sigh.)

**Comment by Theawesomeboophis** [comment]
For snow? Or is this about another issue?

**Comment by Theawesomeboophis** [comment]
I need your help with snow, I'm possibly going to be working on getting https://github.com/CleverRaven/Cataclysm-DDA/issues/45672 finished as well as linting snow and taking any suggestions as to how to implement it from aivean's discussion.

**Comment by actual-nh** [comment]
I'll do my best. (Note that my teaching semester starts on the 7th, and I will be needing to do some prep before it; not sure how much time I will have!)

**Comment by Theawesomeboophis** [comment]
> I'll do my best. (Note that my teaching semester starts on the 7th, and I will be needing to do some prep before it; not sure how much time I will have!)

Understood, teaching physiology sounds like a lot of research and time spent on the field.

**Comment by actual-nh** [comment]
Actually, I tend to hear about things from my more-experienced students asking questions, and then do the research. (Any teacher/professor who is unwilling to say "I don't know; I'll see what I can find out", or to otherwise learn from their students, is not someone who should be teaching. Sorry, pet peeve...) It's Human Anatomy & Physiology - I teach a bunch of people either already in or going into health care. (Due to the ones already in health care, COVID has been a major worry - either managing people doing labs at home or supervising small groups in-person.)

Another part of it is that a lot of my students are not as computer-literate, given age (there are exceptions on this, including myself!)... and COVID has greatly increased how much has to be online. So I also have to have things set up as comprehensibly as possible.

**Comment by Theawesomeboophis** [comment]
https://github.com/Theawesomeboophis/Cataclysm-DDA-Boophis-Mod
This is what I was talking about, I wanted to clear up the confusion.
